// orchestrator/lib/pins.js
//
// Pin (comment) CRUD store. JSON file (orchestrator/state/pins-{playgroundId}.json)
// for persistence + in-memory operations. Shape-compatible with the
// playground-app localStorage pin-store —
//   { id, playgroundId, x, y, text, route, element, commitSha,
//     createdAt, updatedAt, resolvedAt, replies: [{ id, text, createdAt }] }
//
// Synchronous IO (read-on-demand / write-on-mutate). Assumes fewer than 50 pins —
// small file, sync fs is simpler. Switch to async following the lib/molly-metrics
// pattern if needed later.
//
// Multi-user concurrent: last-write-wins. Not a CRDT. Decide after measuring
// collision frequency in production.

import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const STATE_DIR = path.join(__dirname, '..', 'state');

function fileFor(playgroundId) {
  return path.join(STATE_DIR, `pins-${encodeURIComponent(playgroundId)}.json`);
}

function load(playgroundId) {
  try {
    const raw = fs.readFileSync(fileFor(playgroundId), 'utf8');
    const parsed = JSON.parse(raw);
    return Array.isArray(parsed) ? parsed : [];
  } catch {
    return [];
  }
}

function save(playgroundId, pins) {
  try {
    if (!fs.existsSync(STATE_DIR)) fs.mkdirSync(STATE_DIR, { recursive: true });
    fs.writeFileSync(fileFor(playgroundId), JSON.stringify(pins, null, 2));
  } catch (err) {
    console.warn(`[pins] save failed for ${playgroundId}: ${err?.message ?? err}`);
  }
}

/**
 * @param {string} playgroundId
 * @returns {Array<object>} pins
 */
export function listPins(playgroundId) {
  if (!playgroundId) return [];
  return load(playgroundId);
}

/**
 * @param {string} playgroundId
 * @param {object} pin — must include id (generated by the client)
 * @returns {object} the saved pin
 */
export function createPin(playgroundId, pin) {
  if (!playgroundId || !pin?.id) throw new Error('playgroundId + pin.id required');
  const pins = load(playgroundId);
  // Prevent duplicate IDs — if already exists, treat as an update (client retry case)
  const idx = pins.findIndex((p) => p.id === pin.id);
  const stamped = { ...pin, playgroundId, createdAt: pin.createdAt ?? Date.now() };
  if (idx === -1) {
    pins.push(stamped);
  } else {
    pins[idx] = { ...pins[idx], ...stamped };
  }
  save(playgroundId, pins);
  return stamped;
}

/**
 * Partial patch. Unknown fields are spread through as-is.
 */
export function updatePin(playgroundId, pinId, patch) {
  if (!playgroundId || !pinId) return null;
  const pins = load(playgroundId);
  const idx = pins.findIndex((p) => p.id === pinId);
  if (idx === -1) return null;
  pins[idx] = { ...pins[idx], ...patch, updatedAt: Date.now() };
  save(playgroundId, pins);
  return pins[idx];
}

export function deletePin(playgroundId, pinId) {
  if (!playgroundId || !pinId) return false;
  const before = load(playgroundId);
  const after = before.filter((p) => p.id !== pinId);
  if (after.length === before.length) return false;
  save(playgroundId, after);
  return true;
}

export function addReply(playgroundId, pinId, reply) {
  if (!playgroundId || !pinId || !reply?.id) return null;
  const pins = load(playgroundId);
  const pin = pins.find((p) => p.id === pinId);
  if (!pin) return null;
  pin.replies = pin.replies ?? [];
  // Prevent duplicate reply IDs
  const existing = pin.replies.findIndex((r) => r.id === reply.id);
  const stamped = { ...reply, createdAt: reply.createdAt ?? Date.now() };
  if (existing === -1) pin.replies.push(stamped);
  else pin.replies[existing] = { ...pin.replies[existing], ...stamped };
  pin.updatedAt = Date.now();
  save(playgroundId, pins);
  return stamped;
}

export function updateReply(playgroundId, pinId, replyId, patch) {
  if (!playgroundId || !pinId || !replyId) return null;
  const pins = load(playgroundId);
  const pin = pins.find((p) => p.id === pinId);
  if (!pin?.replies) return null;
  const idx = pin.replies.findIndex((r) => r.id === replyId);
  if (idx === -1) return null;
  pin.replies[idx] = { ...pin.replies[idx], ...patch, updatedAt: Date.now() };
  pin.updatedAt = Date.now();
  save(playgroundId, pins);
  return pin.replies[idx];
}

export function deleteReply(playgroundId, pinId, replyId) {
  if (!playgroundId || !pinId || !replyId) return false;
  const pins = load(playgroundId);
  const pin = pins.find((p) => p.id === pinId);
  if (!pin?.replies) return false;
  const before = pin.replies.length;
  pin.replies = pin.replies.filter((r) => r.id !== replyId);
  if (pin.replies.length === before) return false;
  pin.updatedAt = Date.now();
  save(playgroundId, pins);
  return true;
}
